function eegscore(dummy)
% function eegscore(dummy)
%
% This function will display the EEG data in allChannelData and allChannelMask,
% 8 channels at a time, and 2 seconds at a time. The number of channels and
% length of time can be changed interactively. Slider bars can be used to
% scroll through the channels and data. The user can rubberband-select an
% area within the data graphs and mark that area good or bad for selected
% channels.
%

close all
clear all
% Define the global values
eegsinclude;
%addpath [GetPCPBasePath(), '\PCP\Matlab\scripts\Preprocessing\eegscore'];



if (nargin > 0)
	error('Eegscore no longer takes arguments.');
end

%
% Now, load in the color map arrays needed (eegViewColorMap,
%	eegViewColorOrder, eegViewLegendData)
%
load initEEGViewData;
deflColor = [0.8 0.8 0.8];
bgColor = [0.733333 0.733333 0.733333];
% set WorkingFigure = 0 so first call to eegswork creates WorkingFigure
WorkingFigure = 0;
editFigure = 0;
% set eegFigure = 0 so eegsfile recognizes its first call
eegFigure = 0;
%set totChans = 0 so we can use it to check if a file was opened by the calls to eegsfile below
totChans = 0;
% initialize event Channel
eventChannel = 0;
origDir = getenv('PWD');
ScreenSize = get(0, 'ScreenSize');

eegsfile('create');
eegsfile('dialog');
if totChans > 0        %if no file was opened then totChans is still 0 and there's no need to continue
disp('Preparing user interface. One moment please...');


%
% Start by creating the editing options pop-up window. Since it starts off
% as invisible, draw it first, so that there isn't a wierd long delay during
% the drawing of visible stuff.
%
cbeegsopt('create');
%
% Start with the window (figure) description.
%
position = ScreenSize +  [20 50 -40 -100];

eegFigure = figure('BackingStore', 'off', ...
	'Color',deflColor, ...
	'CloseRequestFcn', 'cbeegsview(''cancel'')', ...
	'KeyPressFcn', 'cbeegsview(''keypress'')', ...
	'Colormap',eegViewColorMap, ...
	'MenuBar', 'none', ...
	'Name', 'EEG Data Viewer', ...
	'NumberTitle', 'off', ...
	'Position', position, ...
	'PaperOrientation', 'landscape', ...
	'PaperPosition', [0.5 0.5 10.0 7.5], ...
	'Tag','Fig1');

% create menu items
mnuFile = uimenu(eegFigure,'Label','File');
sbmnuPrint = uimenu('Parent',mnuFile,'Label','Print', ...
	'Callback','cbeegsmenu(''print'');');
%sbmnuNew = uimenu('Parent',mnuFile,'Label','Save Mask', ...
%	'Callback', 'cbeegsfile(''save'')');
sbmnuExit = uimenu('Parent',mnuFile,'Label','Save/Exit', ...
	'Callback', 'cbeegsview(''cancel'')');
mnuOptions = uimenu(eegFigure,'Label','Options');
sbmnuDisplay = uimenu('Parent',mnuOptions,'Label','Fixed Chan Display', ...
	'Callback','cbeegsmenu(''fcDisplay'');' );
sbmnuGoodColor = uimenu('Parent',mnuOptions,'Label','Good Line Color', ...
	'Callback','cbeegsmenu(''goodColor'');' );
sbmnuEvent = uimenu('Parent',mnuOptions,'Label','Set Event Channel', ...
	'Callback', 'cbeegsmenu(''event_chan'');');
mnuCalculate = uimenu(eegFigure,'Label','Calculate');
sbmnuGoodWins = uimenu('Parent',mnuCalculate,'Label','NumGoodWins', ...
	'Callback','cbeegsmenu(''NumGoodWins'');');
mnuHelp = uimenu(eegFigure,'Label','Help');
b = uimenu('Parent',mnuHelp,'Label','New Features', ...
	'Callback', 'eegshelp(''newFeatures'')');
b = uimenu('Parent',mnuHelp,'Label','Channel Settings', ...
	'Callback', 'eegshelp(''chanSettings'')');
b = uimenu('Parent',mnuHelp,'Label','Mark Good/Bad', ...
	'Callback', 'eegshelp(''markGoodBad'')');
b = uimenu('Parent',mnuHelp,'Label','Config File', ...
	'Callback', 'eegshelp(''configFile'')');
b = uimenu('Parent',mnuHelp,'Label','NumGoodWins', ...
	'Callback', 'eegshelp(''numGoodWins'')');


%
% Next come the sub-plot windows (axes) descriptions...
% for data and event channels
%
% for i=1:totChans
for i=1:totChans    
        if chanInfo(i).useMyY == 1
          Ymax = chanInfo(i).maxYValue;  % use channel setting
        else
          Ymax = maxYValue;         % use global setting
        end
	eegPlotList(i) = axes('Parent',eegFigure, ...
		'Box','on', ...
		'CameraUpVector',[0 1 0], ...
		'Color',[1 1 1], ...
		'ColorOrder',eegViewColorOrder, ...
		'NextPlot','add', ...
		'Position',[0.08 0.95 0.75 0.1], ...
		'XColor',deflColor, ...
		'XLim',[0 xSecsWidth], ...
		'XLimMode','manual', ...
		'YColor',deflColor, ...
		'YLim',[-Ymax Ymax], ...
		'YLimMode','manual', ...
		'Visible','off', ...
		'ZColor',[0 0 0]);
end
%
% Next is the legend
%

b = axes('Parent',eegFigure, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',eegViewColorOrder, ...
	'DrawMode','fast', ...
	'FontUnits', 'normalized', ...
	'FontSize',0.18, ...
	'NextPlot','add', ...
	'Position',[0.92 0.90 0.07 0.07], ...
	'UserData',eegViewLegendData, ...
	'XColor',[0 0 0], ...
	'XLimMode','manual', ...
	'XTick',-1, ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YLimMode','manual', ...
	'YTick',-1, ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'FontUnits', 'normalized', ...
	'FontSize',0.18, ...
	'Position',[0.666667 0.75 0], ...
	'String','OK', ...
	'Tag','legendText6');
c = line('Parent',b, ...
	'Color',[0 0.5 0], ...
	'XData',[0.08 0.4], ...
	'YData',[0.75 0.75]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'FontUnits', 'normalized', ...
	'FontSize',0.18, ...
	'Position',[0.666667 0.5 0], ...
	'String','BAD');
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'XData',[0.08 0.4], ...
	'YData',[0.5 0.5]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'FontUnits', 'normalized', ...
	'FontSize',0.18, ...
	'Position',[0.09 0.15 0], ...
	'String','X: secs   Y:  \muV');

%
% Now for the sliders: time is horizontal, channel is (upside down) vertical
%
%sliderStep = (Samp_Rate * xSecsWidth)/NSamp;
sliderStep = xSecsWidth/(NSamp/Samp_Rate - xSecsWidth);  % test
if sliderStep > 1
	sliderStep = 1.0;
end
sliderMax = ((NSamp)/ Samp_Rate) - xSecsWidth;
%make sure sliderMax is at least 0.01
sliderMax = max(sliderMax,0.01);
timeSlider = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'Callback', 'cbeegsview(''time_cb'')', ...
	'BackgroundColor',bgColor, ...
	'HandleVisibility', 'callback', ...
	'Max',sliderMax, ...
	'Min',0, ...
	'Position',[0.08 0.02 0.75 0.04], ...
	'SliderStep',[sliderStep/1.25 sliderStep], ...
	'String','Time', ...
	'Style','slider', ...
	'Tag','SliderT', ...
	'Value', timeStart);


prevButton = uicontrol('Parent',eegFigure, ...
	'Style', 'pushbutton', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''previous'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.30, ...
	'Position',[0.63 0.951 0.10 0.04], ...
	'String','PrevBad', ...
	'Tag', 'prevButton');

nextButton = uicontrol('Parent',eegFigure, ...
	'Style', 'pushbutton', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''next'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.30, ...
	'Position',[0.73 0.951 0.10 0.04], ...
	'String','NextBad', ...
	'Tag', 'nextButton');

prevEvent = uicontrol('Parent',eegFigure, ...
	'Style', 'pushbutton', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''prevEvent'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.30, ...
	'Position',[0.63 0.07 0.10 0.04], ...
	'String','PrevEvent', ...
	'Tag', 'prevEvent');

nextEvent = uicontrol('Parent',eegFigure, ...
	'Style', 'pushbutton', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''nextEvent'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.30, ...
	'Position',[0.73 0.07 0.10 0.04], ...
	'String','NextEvent', ...
	'Tag', 'nextEvent');

% turn these off for now if there are no events
if NEvent == 0
	set(prevEvent,'Visible','off');
	set(nextEvent,'Visible','off');
end
channelSlider = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'Callback', 'cbeegsview(''chan_cb'')', ...
	'BackgroundColor',bgColor, ...
	'HandleVisibility', 'callback', ...
	'Max',1, ...
	'Min',0, ...
	'Position',[0.015 0.15 0.025 0.8], ...
	'SliderStep', [0.5 1.0], ...
	'String','Channel', ...
	'Style','slider', ...
	'Tag','SliderC', ...
	'Value',1);

setChanSlider;

yInButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''y_in'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.78 0.07 0.05], ...
	'String','Y In', ...
	'Tag','ButtonYIn');

yOutButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''y_out'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.83 0.07 0.05], ...
	'String','Y Out', ...
	'Tag','ButtonYOut');

xInButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''x_in'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.10, ...
	'Position',[0.92 0.65 0.035 0.1], ...
	'String','X In', ...
	'Tag','ButtonXIn');

xOutButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''x_out'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.10, ...
	'Position',[0.955 0.65 0.035 0.1], ...
	'String','X Out', ...
	'Tag','ButtonXOut');

fewerChansButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''fewer_channels'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.53 0.07 0.05], ...
	'String','- Chan', ...
	'Tag','ButtonLessChan');

moreChansButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''more_channels'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.58 0.07 0.05], ...
	'String','+ Chan', ...
	'Tag','ButtonMoreChan');

editChansButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''edit_channels'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.18, ...
	'Position',[0.92 0.45 0.07 0.05], ...
	'String','Chan settings', ...
	'Tag','ButtonEditChan');

undoButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''undo'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.25 0.07 0.09], ...
	'String','UNDO', ...
	'Visible','off', ...
	'Tag','ButtonUndo');

%fileButton = uicontrol('Parent',eegFigure, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback', 'cbeegsfile(''save'')', ...
%	'BackgroundColor',bgColor, ...
%	'FontSize',0.25, ...
%	'Position',[0.92 0.10 0.07 0.05], ...
%	'String','Save Mask', ...
%	'Tag','ButtonFile');

exitButton = uicontrol('Parent',eegFigure, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsview(''cancel'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.25, ...
	'Position',[0.92 0.10 0.07 0.05], ...
	'String','Save/Exit', ...
	'Tag','ButtonExit');

% put in axes to match size of eegFigure so that plot labels can be added as text
labelAxes = axes('Parent',eegFigure, ...
	'Position',[0 0 1 1], ...
	'Color', 'none', ...
	'XColor', deflColor, ...
	'YColor', deflColor, ...
	'Visible', 'off', ...
	'Tag', 'LABELAXES');

% add current work file name above axes and to window name
text(0.08,0.96,datFileName,'Parent',labelAxes, ...
	'Interpreter','none', 'Tag', 'fileLabel',...
	'FontUnits','normalized','Fontsize',0.017,'Color',[0 0 1]);
set(eegFigure,'Name',['EEG Data Viewer: ' datFileName]);
eegsplot([]);
end   %if totChans > 0
