global fileButton h;
h = figure('KeyPressFcn', 'cbkeypress');
fileButton = uicontrol('Parent',h, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbfig(''msg'')', ...
	'BackgroundColor',[.73 .73 .73], ...
	'FontSize',0.25, ...
	'Position',[0.92 0.10 0.07 0.05], ...
	'String','Files', ...
	'Tag','ButtonFile');
set(0,'CurrentFigure', h);



