function err = testFigClose;

helpText(1,1) = {'This is a test'};

h = figure('Name','Test');
b = uicontrol('Parent', h, ...
	'Style','pushButton', ...
	'String','Close', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'Units', 'normalized', ...
	'Position',[0.40 0.05 0.20 0.05], ...
	'Callback','close(h)');
textpos =  [0.05 0.15 0.9 0.8];
%t = uicontrol('Parent', h, ...
%	'Style', 'text', ...
%	'BackgroundColor', [1 1 1], ...
%	'Units', 'normalized', ...
%	'Position', textpos, ...
%	'Fontsize', 14, ...
%	'HorizontalAlignment','left');
%outstring = textwrap(t,helpText);
%set(t,'String',outstring);
