% script to display instructions for eegscore
position = [200 200 500 600];
bgColor = [1 1 1]*0.8;
helpFig = figure('BackingStore', 'off','Name', 'EEGSCORE Description', ...
	'NumberTitle', 'off', ...
	'Position',position, 'Color', bgColor, ...
	'Menubar', 'none');
textpos =  [0 50 500 550];
helpText = {['     eegscoreNEW requires a more complicated configuration file than the previous version. After you hit load it will prompt you whether to create a default config file or to open an existing one. Choose default if this is the first time scoring this type of data.  A basic configuration file will be created which tells eegscoreNEW to display the channels in numerical order with channels named with their display number, and no fixed channels or channel with adjusted range or bias. At the end of the scoring session you will be prompted to save the configuration file with all the modifications made during the session.'], ...
['     After you click chan settings to open the channel edit window, first click on the channel you want to edit in the listbox in the upper left, you can then use the up/down arrow keys to scroll through the channels and see each ones settings. Once a particular channel is selected its properties can be edited in the appropriate windows. The use range/offset button must be selected for the input values to be used. The other channels which dont have use range/offset checked are controlled by the Yin, Yout buttons.'], ...
['      Vertical scales are now located on alternating ends of the plots since they all could have different scales and need to be labelled. Selecting data with the left button marks it bad, with the right button good; or you can change your mind in the Edit Options window as before.  Click on the numGoodWins button to compute the total number of good 1sec/0.5sec overlap windows in the scored data. This needs to be manually updated after additional scoring since it can take about 20s on 128 channel data.'], ... 
['     Upon exiting or choosing another file the option to change the name for the saved config file is given in case it might be useful for a particular type of file left to be scored.']}; 
h = uicontrol('Parent', helpFig, 'Style', 'text', ...
	'BackgroundColor', [1 1 1], ...
	'Position', textpos, ...
	'Fontsize', 14, ...
	'HorizontalAlignment','left');
outstring = textwrap(h,helpText);
set(h,'String',outstring);
