h02301
s 00249/00000/00000
d D 1.1 01/07/06 11:37:31 greischar 1 0
c date and time created 01/07/06 11:37:31 by greischar
e
u
U
f e 0
t
T
I 1
function cbeegseditchan(action)
%
% This is the callback function for editchannels
%

% Define globals
eegsinclude;

switch action
case 'create',
% set up Cell array for channel popupmenu
for i=1:totChans
	chanCell(i) = {num2str(i)};
end
editChannels = figure('Color',deflColor, ...
	'Visible','on', ...
	'CloseRequestFcn', 'cbeegsopt(''cancel'')', ...
	'KeyPressFcn', 'cbeegsopt(''keypress'')', ...
	'Colormap',eegViewColorMap, ...
	'MenuBar', 'none', ...
	'Name', 'Channel Settings', ...
	'NumberTitle', 'off', ...
	'Position',[80 180 425 275], ...
	'Tag','editChannels');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','cbeegseditchan(''doit'')', ...
	'Position',[0.35 0.05 0.30 0.20], ...
	'String','Doit!', ...
	'Tag','Push_Doit');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'HorizontalAlignment','right', ...
	'Position',[0.05 0.80 0.14 0.10], ...
	'String','Channel:', ...
	'Style','text', ...
	'Tag','cstext1');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','cbeegseditchan(''update'')', ...
	'Position',[0.20 0.50 0.25 0.40], ...
	'Style','listbox', ...
	'String',chanCell, ...
	'Value', 1, ...
	'Tag','channel');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','cbeegseditchan(''name'')', ...
	'Position',[0.20 0.35 0.25 0.10], ...
	'Style','edit', ...
	'Tag','name');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'HorizontalAlignment','right', ...
	'Position',[0.50 0.80 0.25 0.10], ...
	'String','DisplayOrder:', ...
	'Style','text', ...
	'Tag','cstext2');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','cbeegseditchan(''displayOrder'')', ...
	'Position',[0.76 0.80 0.19 0.10], ...
	'Style','edit', ...
	'Tag','displayorder');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'HorizontalAlignment','right', ...
	'Position',[0.05 0.35 0.14 0.10], ...
	'String','Name:', ...
	'Style','text', ...
	'Tag','cstext3');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'HorizontalAlignment','right', ...
	'Position',[0.50 0.65 0.25 0.10], ...
	'String','Range:', ...
	'Style','text', ...
	'Tag','cstext4');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'HorizontalAlignment','right', ...
	'Position',[0.50 0.50 0.25 0.10], ...
	'String','Offset:', ...
	'Style','text', ...
	'Tag','cstext5');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','cbeegseditchan(''range'')', ...
	'Position',[0.76 0.65 0.19 0.10], ...
	'Style','edit', ...
	'Tag','range');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','cbeegseditchan(''offset'')', ...
	'Position',[0.76 0.50 0.19 0.10], ...
	'Style','edit', ...
	'Tag','offset');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','cbeegseditchan(''use_range'')', ...
	'Position',[0.50 0.35 0.45 0.10], ...
	'String','Use Range/Offset (else defaults)', ...
	'Style','radiobutton', ...
	'Tag','userange');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','cbeegseditchan(''visible'')', ...
	'Position',[0.05 0.20 0.14 0.10], ...
	'String','Visible', ...
	'Style','radiobutton', ...
	'Tag','visible');
b = uicontrol('Parent',editChannels, ...
	'Visible','on', ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','cbeegseditchan(''fixed'')', ...
	'Position',[0.05 0.05 0.14 0.10], ...
	'String','Fixed', ...
	'Style','radiobutton', ...
	'Tag','fixed');

case 'update',
	index = get(findobj(editChannels,'Tag','channel'), 'Value');
	inCell = get(findobj(editChannels,'Tag','channel'), 'String');	
	i = str2num(inCell{index});
	set(findobj(editChannels,'Tag','name'), 'String', chanInfo(i).name);
	set(findobj(editChannels,'Tag','displayorder'), 'String', num2str(chanInfo(i).displayOrder));
	set(findobj(editChannels,'Tag','range'), 'String', num2str(chanInfo(i).maxYValue));
	set(findobj(editChannels,'Tag','offset'), 'String', num2str(chanInfo(i).yOffset));
	if chanInfo(i).useMyY
		set(findobj(editChannels,'Tag','userange'), 'Value', 1);
	else
		set(findobj(editChannels,'Tag','userange'), 'Value', 0);
	end
	if chanInfo(i).isVisible
		set(findobj(editChannels,'Tag','visible'), 'Value', 1);
	else
		set(findobj(editChannels,'Tag','visible'), 'Value', 0);
	end
	if chanInfo(i).fixed
		set(findobj(editChannels,'Tag','fixed'), 'Value', 1);
	else
		set(findobj(editChannels,'Tag','fixed'), 'Value', 0);
	end

case 'name',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).name = get(findobj(editChannels,'Tag','name'), 'String');
%	set(eegChanText(i),'String',chanInfo(i).name);
	cbeegseditchan('update');


case 'displayOrder',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	newpos = str2num(get(findobj(editChannels,'Tag','displayorder'), 'String'));
	oldpos = find(KeepOrder == i);
	if oldpos > newpos
		for j = oldpos:-1:newpos+1
			KeepOrder(j) = KeepOrder(j-1);
		end
		KeepOrder(newpos) = i;
	else
		for j = oldpos:newpos-1
			KeepOrder(j) = KeepOrder(j+1);
		end
		KeepOrder(newpos) = i;
	end
	for j=1:totChans
		chanInfo(j).displayOrder = find(KeepOrder == j);
	end
	eegsBuildDisplayOrder;
	cbeegseditchan('update');

case 'range',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).maxYValue = str2num(get(findobj(editChannels,'Tag','range'), 'String'));
	cbeegseditchan('update');

case 'offset',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).yOffset = str2num(get(findobj(editChannels,'Tag','offset'), 'String'));
	cbeegseditchan('update');

case 'use_range',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).useMyY = get(findobj(editChannels,'Tag','userange'), 'Value');
	cbeegseditchan('update');

case 'visible',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).isVisible = get(findobj(editChannels,'Tag','visible'), 'Value');
	cbeegseditchan('update');

case 'fixed',
	i = get(findobj(editChannels,'Tag','channel'), 'Value');
	chanInfo(i).fixed = get(findobj(editChannels,'Tag','fixed'), 'Value');
%	if chanInfo(i).fixed ==1
%		set(eegChanText(i),'Color', [0 0 0]);
%	else
%		set(eegChanText(i),'Color', [0 0 1]);
%	end
	cbeegseditchan('update');
   
case 'doit',
   set(editChannels, 'Visible','off');
	kids = get(editChannels, 'Children');
	for kidNum = 1:size(kids,1)
		set(kids(kidNum), 'Visible','off');
	end
	eegsBuildDisplayOrder;
	% make sure numChansShown is less than or equal to number of channels in DisplayOrder
	while numChansShown > length(DisplayOrder)
		numChansShown = numChansShown/2;
	end
	setChanSlider;
	displayNeedsRefresh = 1;
	eegsplot([]);


otherwise,
	disp(action);
end

E 1
