h07130
s 00518/00000/00000
d D 1.1 01/07/06 11:38:08 greischar 1 0
c date and time created 01/07/06 11:38:08 by greischar
e
u
U
f e 0
t
T
I 1
function cbeegsopt(action)

% This is the callback function for the eegscore() function
% when the editing options pop-up window is visible.
%
% It is not intended for external use.

% Define the global values
eegsinclude;

switch action

case 'create',
editFigure = figure('Color',deflColor, ...
	'Visible','off', ...
	'CloseRequestFcn', 'cbeegsopt(''cancel'')', ...
	'KeyPressFcn', 'cbeegsopt(''keypress'')', ...
	'Colormap',eegViewColorMap, ...
	'MenuBar', 'none', ...
	'Name', 'Editing Options', ...
	'NumberTitle', 'off', ...
	'Position',[400 150 400 250], ...
	'Tag','Fig2');

b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'BackgroundColor',deflColor, ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'Position',[0.05 0.9 0.6 0.1], ...
	'String','Apply selection to:', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''channel_range'')', ...
	'Value', 1, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.8 0.1 0.1], ...
	'Tag','channels', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''channel_all'')', ...
	'Value', 0, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.675 0.1 0.1], ...
	'Tag','allchannels', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.8 0.3 0.1], ...
	'String','Channels', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.46 0.8 0.17 0.11], ...
	'Tag','minchan', ...
	'Style','text');                         %test
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'BackgroundColor',deflColor, ...
	'HorizontalAlignment','left', ...
	'Position',[0.64 0.8 0.04 0.1], ...
	'String','to', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.68 0.8 0.17 0.11], ...
	'Tag','maxchan', ...
	'Style','text');                        %test
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.87 0.8 0.6 0.1], ...
	'String','Chan', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.675 0.6 0.1], ...
	'String','All Channels', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.87 0.675 0.6 0.1], ...
	'String','Samp', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.05 0.275 0.4 0.1], ...
	'String','Selection is:', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''mark_good'')', ...
	'Value', 0, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.175 0.1 0.1], ...
	'Tag','ok', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''mark_bad'')', ...
	'Value', 1, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.05 0.1 0.1], ...
	'Tag','bad', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.175 0.12 0.1], ...
	'String','OK', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.05 0.15 0.1], ...
	'String','Bad', ...
	'Style','text');

b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''doit'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.34 0.15 0.3 0.125], ...
	'Tag','doit', ...
	'String','Do It!');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''cancel'')', ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.68 0.15 0.3 0.125], ...
	'Tag','cancel', ...
	'String','Cancel');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''time_range'')', ...
	'Value', 1, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.525 0.1 0.1], ...
	'Tag','seconds', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''time_all'')', ...
	'Value', 0, ...
	'BackgroundColor',bgColor, ...
	'FontSize',0.4, ...
	'Position',[0.06 0.4 0.1 0.1], ...
	'Tag','alltimes', ...
	'Style','radiobutton');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.525 0.3 0.1], ...
	'String','Seconds', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.87 0.525 0.3 0.1], ...
	'String','Secs', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''mintime'')', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.46 0.525 0.17 0.11], ...
	'Tag','mintime', ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'BackgroundColor',deflColor, ...
	'HorizontalAlignment','left', ...
	'Position',[0.64 0.525 0.04 0.1], ...
	'String','to', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'BackgroundColor',deflColor, ...
	'HorizontalAlignment','left', ...
	'Position',[0.64 0.66 0.04 0.1], ...
	'String','to', ...
	'Style','text');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''maxtime'')', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.68 0.525 0.17 0.11], ...
	'Tag','maxtime', ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Tag','frequency', ...
	'Position',[0.68 0.40 0.17 0.11], ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''minsamp'')', ...
        'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.46 0.66 0.17 0.11], ...
	'Tag','minsamp', ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback', 'cbeegsopt(''maxsamp'')', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.68 0.66 0.17 0.11], ...
	'Tag','maxsamp', ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'Position',[0.46 0.40 0.17 0.11], ...
	'Tag','deltat', ...
	'Style','edit');
b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.68,0.3 0.2 0.1], ...
	'String','Frequency', ...
	'Style','text');

h = axes('Parent',editFigure, ...
	'Position', [0 0 1 1], ...
	'Color', deflColor, ...
	'XColor', deflColor, ...
	'YColor', deflColor, ...
	'Visible', 'off', ...
	'Tag', 'dt_axes');
	text(0.53,0.36,'\Delta T','FontSize',14);

b = uicontrol('Parent',editFigure, ...
	'Visible','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.4, ...
	'HorizontalAlignment','left', ...
	'BackgroundColor',deflColor, ...
	'Position',[0.185 0.4 0.2 0.1], ...
	'String','All Times', ...
	'Style','text');

case 'channel_range',                   % toggle buttons
	set(findobj(editFigure,'Tag', 'channels'), 'Value', 1);
	set(findobj(editFigure,'Tag', 'allchannels'), 'Value', 0);

case 'channel_all',
	set(findobj(editFigure,'Tag', 'channels'), 'Value', 0);
	set(findobj(editFigure,'Tag', 'allchannels'), 'Value', 1);

case 'time_range',
	set(findobj(editFigure,'Tag', 'seconds'), 'Value', 1);
	set(findobj(editFigure,'Tag', 'alltimes'), 'Value', 0);

case 'time_all',
	set(findobj(editFigure,'Tag', 'seconds'), 'Value', 0);
	set(findobj(editFigure,'Tag', 'alltimes'), 'Value', 1);

case 'mark_good',
	set(findobj(editFigure,'Tag', 'ok'), 'Value', 1);
	set(findobj(editFigure,'Tag', 'bad'), 'Value', 0);

case 'mark_bad',
	set(findobj(editFigure,'Tag', 'ok'), 'Value', 0);
	set(findobj(editFigure,'Tag', 'bad'), 'Value', 1);

case 'mintime',
   TimeMin = str2num(get(findobj(editFigure,'Tag', 'mintime'), 'String'));
   SampMin = TimeMin*Samp_Rate + 1;                     %sample 1 at t=0
   strSampMin = sprintf('%d',SampMin);
   set(findobj(editFigure,'Tag', 'minsamp'), 'String', strSampMin);     %reset Sample Number
   TimeMax = str2num(get(findobj(editFigure,'Tag', 'maxtime'), 'String'));
   DiffTime = TimeMax - TimeMin;
   strDiffTime = sprintf('%.3f',DiffTime);
   set(findobj(editFigure,'Tag', 'deltat'), 'String', strDiffTime);    %reset delta T
   Freq = 1/DiffTime;
   strFreq = sprintf('%.1f',Freq);
   set(findobj(editFigure,'Tag', 'frequency'),'String',strFreq);          %reset Frequency
case 'maxtime',
   TimeMax = str2num(get(findobj(editFigure,'Tag', 'maxtime'), 'String'));
   SampMax = TimeMax*Samp_Rate + 1;
   strSampMax = sprintf('%d',SampMax);
   set(findobj(editFigure,'Tag', 'maxsamp'), 'String', strSampMax);     %reset Sample Number
   TimeMin = str2num(get(findobj(editFigure,'Tag', 'mintime'), 'String'));
   DiffTime = TimeMax - TimeMin;
   strDiffTime = sprintf('%.3f',DiffTime);
   set(findobj(editFigure,'Tag', 'deltat'), 'String', strDiffTime);     %reset delta T
   Freq = 1/DiffTime;
   strFreq = sprintf('%.1f',Freq);
   set(findobj(editFigure,'Tag', 'frequency'),'String',strFreq);          %reset Frequency
case 'minsamp',
   SampMin = str2num(get(findobj(editFigure,'Tag', 'minsamp'), 'String'));
   TimeMin = (SampMin - 1)/Samp_Rate;
   strTimeMin = sprintf('%.3f',TimeMin);
   set(findobj(editFigure,'Tag', 'mintime'), 'String', strTimeMin);         %reset Time min
   TimeMax = str2num(get(findobj(editFigure,'Tag', 'maxtime'), 'String'));
   DiffTime = TimeMax - TimeMin;
   strDiffTime = sprintf('%.3f',DiffTime);
   set(findobj(editFigure,'Tag', 'deltat'), 'String', strDiffTime);        %reset delta T
   Freq = 1/DiffTime;
   strFreq = sprintf('%.1f',Freq);
   set(findobj(editFigure,'Tag', 'frequency'), 'String', strFreq);          %reset Frequency
case 'maxsamp',
   SampMax = str2num(get(findobj(editFigure,'Tag', 'maxsamp'), 'String'));
   TimeMax = (SampMax - 1)/Samp_Rate;
   strTimeMax = sprintf('%.3f',TimeMax);
   set(findobj(editFigure,'Tag', 'maxtime'), 'String', strTimeMax);        %reset Time max
   TimeMin = str2num(get(findobj(editFigure,'Tag', 'mintime'), 'String'));
   DiffTime = TimeMax - TimeMin;
   strDiffTime = sprintf('%.3f',DiffTime);
   set(findobj(editFigure,'Tag', 'deltat'), 'String', strDiffTime);        %reset delta T
   Freq = 1/DiffTime;
   strFreq = sprintf('%.1f',Freq);
   set(findobj(editFigure,'Tag', 'frequency'),'String',strFreq);          %reset Frequency
case 'doit',
	selAllChan = get(findobj(editFigure,'Tag', 'allchannels'), 'Value');
	selAllTime = get(findobj(editFigure,'Tag', 'alltimes'), 'Value');
	if (selAllTime == 1) & (selAllChan == 1)
		warndlg('All Channels and All Times are both selected!', ...
			'Huh?');
	else
		% Invisiblize the edit window
		set(editFigure, 'Visible','off');
		set(0,'CurrentFigure',eegFigure);
		kids = get(editFigure, 'Children');
		for kidNum = 1:size(kids,1)
			set(kids(kidNum), 'Visible','off');
		end

		% Turn on the "working..." message.
		eegswork('on');

		if selAllChan == 1
			chanMin = 1;
			chanMax = totChans;
			selectedChannels = DisplayOrder;
                 % Return buttons to original setup
                	set(findobj(editFigure,'Tag', 'channels'), 'Value', 1);
                	set(findobj(editFigure,'Tag', 'allchannels'), 'Value', 0);
        	else
			chanMin = str2num(get(findobj(editFigure,'Tag', 'channels'), 'String'));
			chanMin = min(max(chanMin, 1), totChans);
                        chanMax = str2num(get(findobj(editFigure,'Tag', 'allchannels'), 'String'));
                        chanMax = min(max(chanMax, chanMin), totChans);
		end

		
          % reset markSetting button to default of 'Bad'
		markSetting = get(findobj(editFigure,'Tag', 'ok'), 'Value');
                if markSetting
                   set(findobj(editFigure,'Tag', 'ok'), 'Value', 0);
                   set(findobj(editFigure,'Tag', 'bad'), 'Value', 1);
                end
		set(undoButton, 'Visible','on');
		undoMask = allChannelMask;

		% Erase the selection lines in the data windows
		delete(selectedLine);
		if selAllTime == 1
			sampStart = 1;
			sampEnd = NSamp;
                 % Return buttons to original setup
                        set(findobj(editFigure,'Tag', 'seconds'), 'Value', 1);
                        set(findobj(editFigure,'Tag', 'alltimes'), 'Value', 0);
		else
               		sampStart = str2num(get(findobj(editFigure,'Tag', 'minsamp'), 'String'));
			sampStart = min(max(sampStart, 1), NSamp);
             		sampEnd = str2num(get(findobj(editFigure,'Tag', 'maxsamp'), 'String'));
			sampEnd = min(max(sampEnd, sampStart), NSamp);
		end
                allChannelMask(sampStart:sampEnd,selectedChannels) = markSetting;
        end  %if else
	changesMade = changesMade + 1;
	eegsplot([]);
	inEditMode = 0;

case 'cancel',
	set(editFigure, 'Visible','off');
	kids = get(editFigure, 'Children');
	for kidNum = 1:size(kids,1)
		set(kids(kidNum), 'Visible','off');
	end
	delete(selectedLine);
	% reset markSetting button to default of 'Bad'
 	markSetting = get(findobj(editFigure,'Tag', 'ok'), 'Value');
        if markSetting
        	set(findobj(editFigure,'Tag', 'ok'), 'Value', 0);
        	set(findobj(editFigure,'Tag', 'bad'), 'Value', 1);
        end
	
	eegsplot([]);
	inEditMode = 0;
	
case 'keypress',
	k = abs(get(get(0,'CurrentFigure'), 'CurrentCharacter'));
	if k==13
		cbeegsopt('doit');
	end

otherwise,
	disp(action);

end
E 1
